### ISSUE TITLE
`SPECIAL2` instruction `VMONE` should probably be `VMOVE`

### ISSUE THREAD

**Issue by JayFoxRox** [PSI-Rockin/ps2tek#3]
Can't find any mentions of `vmone` in other places, but `vmove` appears to be missing; so I assume this is a typo

https://github.com/PSI-Rockin/ps2tek/blob/04f2a902a94a29097eacb538ad3f3a03f19551bb/index.html#L672

**Comment by PSI-Rockin** [comment]
This is correct, the instruction is VMOVE. Will fix.

**Comment by PSI-Rockin** [comment]
This issue should be fixed, as well as all other issues. Please let me know if you find anymore errors.
